# Generated by Django 4.2.1 on 2023-06-20 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('cantidad_de_jugadores', models.IntegerField(default=0)),
                ('cantidad_de_puntos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de creación')),
            ],
        ),
    ]
