# Generated by Django 4.2.1 on 2023-05-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_equipo', models.CharField(max_length=100)),
                ('nombre_liga', models.CharField(max_length=100)),
                ('cantidad_de_jugadores', models.IntegerField()),
            ],
        ),
    ]
