# Generated by Django 4.2.1 on 2023-05-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('cantidad_de_jugadores', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Liga',
        ),
    ]
