# Generated by Django 4.2.1 on 2023-05-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
