# Generated by Django 4.2.1 on 2023-05-29 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_delete_liga'),
        ('jugador', '0002_delete_equipo_jugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
    ]
