# Generated by Django 4.2.1 on 2023-06-16 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_delete_liga'),
        ('jugador', '0004_alter_jugador_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo', verbose_name='equipo'),
        ),
    ]
